name: Metrics
on:
  schedule:
    - cron: 0 0 * * *
  push: {}
  pull_request: {}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          repositories: 1000
          retries: 10
          repositories_affiliations: owner, collaborator
          base: ""
          config_order: github.achievements, github.reactions
          template: classic
          config_timezone: Europe/Zurich
          
          plugin_achievements: true
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
          
          plugin_reactions: true
          plugin_reactions_limit: 1000
          plugin_reactions_display: absolute
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
